[package]
name = "ldap-rest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ldap3 = "0.11.3"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
hickory-client = "0.24.0"
elliptic-curve = { version = "0.13.8", features = ["pkcs8", "pem"] }
p521 = { version = "0.13.3", features = ["pkcs8", "pem"] }
rand_chacha = "0.3.1"
rand = "0.8.5"
rand_core = "0.6.4"
pretty_env_logger = "0.5.0"
log = "0.4.21"
